### PR TITLE
Add support for docker installation

### PR DESCRIPTION
**Pull request by mostafahussein**
This PR adds support for installing `joomscan` as a docker container

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
great contribution, @rezasp  please consider this PR.

**Comment by Ali-Razmjoo** [comment]
Hi @mostafahussein,

once again thanks for your contribution, it's a great idea to have dockerfile on this project, here are my comments on this PR.

* `dockerfile` works fine, but please add a new line to and mount `reports` folder to `/home/joomscan/reports` and let users access the report files through the host machine. users will not be able change entrypoint to `/bin/bash` without modifying the `dockerfile`.
* since we have opensource license and everyone are welcomed to contribute this project, this line is unnecessary `LABEL maintainer="Mostafa Hussein <mostafa.hussein91@gmail.com>"` please remove it.

Thank you.

**Comment by mostafahussein** [comment]
@Ali-Razmjoo , Can I change it to author instead of maintainer ?

**Comment by mostafahussein** [comment]
for the /home/joomscan/reports part it can be added during creating a new container as the following:

```
docker run -v /path/on/host:/home/joomscan/reports --name joomscan_container rezasp/joomscan
```

This will makes you able to access the reports through the host, also you can use docker-compose as it provides an easier way to handle docker instead of the docker cli itself

In order to modify the entrypoint without modifying the dockerfile you can do the following:

```
docker run -v /path/on/host:/home/joomscan/reports --name joomscan_container --entrypoint /bin/bash rezasp/joomscan
```
I think it will be suitable to add these examples in the readme file itself without modifying the current dockerfile. what do you think ?

**Comment by Ali-Razmjoo** [comment]
I talked to Reza, he also confirmed, it's ok to add your name as a comment in Dockerfile. in that case please modify the readme file and add the docker section.

**Comment by mostafahussein** [comment]
@Ali-Razmjoo , I have updated the dockerfile and the readme kindly check it and let me if there is any modification needed

**Comment by Ali-Razmjoo** [comment]
@mostafahussein  thanks for your contribution.

@rezasp it's ready to merge. please consider.

**Comment by rezasp** [comment]
Hello,

Thank you for your contribution, PR Merged.

Best Regards.

**Pull request merged**
